# configuration
application:
    port: 8888
    host: 127.0.0.1
database:
    host: "localhost"
    port: 3306
    username: "lokoda"
    password: "password"
    database_name: "lokoda"
email:
    host: "smtp.mailtrap.io"
    port: 2525
    username: "c933b743432546"
    password: "33c8bd61bd8d45"

